export { default as BasicLayout } from './components/basic/BasicLayout.vue'
export { default as TopSideLayout } from './components/top-side/TopSideLayout.vue'
export { default as SideLayout } from './components/side/SideLayout.vue'
export { default as LayoutHeader } from './components/components/Header/index.vue'
export { default as LayoutFooter } from './components/components/Footer/index.vue'
